spring:
  application:
    name: meme-service
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:memedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

app:
  services:
    user-service:
      url: http://localhost:8081
    category-service:
      url: http://localhost:8082

logging:
  level:
    com.memelandia.meme: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:memedb
    driver-class-name: org.h2.Driver

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/memedb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect